import { useEffect, useMemo, useRef, useState } from 'react'
import {
  Activity, ArrowUpRight, Check, ChevronDown, CircleAlert, Clock3, Command, Cpu, Database,
  FileText, Layers3, Mic, MoreHorizontal, Orbit, PanelRight, RotateCw, Search, Send,
  ShieldCheck, Sparkles, TerminalSquare, X, Zap, Eye, LockKeyhole, BrainCircuit, Plus,
} from 'lucide-react'

type NexusState = 'idle' | 'listening' | 'processing' | 'responding' | 'executing' | 'verifying' | 'success' | 'warning' | 'error' | 'recovery'
type Mode = 'CONVERSATION' | 'TASK' | 'ACTIVITY' | 'EVIDENCE' | 'SYSTEM'

const stateMeta: Record<NexusState, { label: string; eyebrow: string; accent: string }> = {
  idle: { label: 'Standing by', eyebrow: 'NEXUS CORE', accent: 'cyan' }, listening: { label: 'Listening', eyebrow: 'VOICE CHANNEL', accent: 'violet' }, processing: { label: 'Processing', eyebrow: 'NEURAL PROCESS', accent: 'cyan' }, responding: { label: 'Responding', eyebrow: 'NEXUS CORE', accent: 'cyan' }, executing: { label: 'Executing task', eyebrow: 'ACTION LAYER', accent: 'amber' }, verifying: { label: 'Verifying result', eyebrow: 'PROVENANCE', accent: 'violet' }, success: { label: 'Complete', eyebrow: 'SYSTEM EVENT', accent: 'emerald' }, warning: { label: 'Needs attention', eyebrow: 'SYSTEM EVENT', accent: 'amber' }, error: { label: 'Action blocked', eyebrow: 'SYSTEM EVENT', accent: 'rose' }, recovery: { label: 'Recovering', eyebrow: 'RECOVERY LAYER', accent: 'cyan' },
}
const steps = [
  ['Interpret request', 'Intent and constraints resolved', 'completed'],
  ['Inspect workspace', 'Reading available context', 'completed'],
  ['Prepare response', 'Synthesizing grounded result', 'running'],
  ['Verify output', 'Awaiting execution state', 'queued'],
] as const

function Core({ state }: { state: NexusState }) {
  const meta = stateMeta[state]
  return <div className={`core-stage core-${meta.accent} core-state-${state}`} aria-label={`Nexus Core ${meta.label}`}>
    <div className="core-aura aura-one" /><div className="core-aura aura-two" />
    <div className="core-orbit orbit-one" /><div className="core-orbit orbit-two" /><div className="core-orbit orbit-three" /><div className="core-orbit orbit-four" />
    <div className="core-scan" /><div className="core-halo" />
    <div className="core-shell"><div className="core-grid" /><div className="core-lattice" /><div className="core-filament filament-a" /><div className="core-filament filament-b" /><div className="core-center"><Orbit size={38} strokeWidth={1.1} /></div></div>
    <div className="core-caption"><span className="eyebrow">{meta.eyebrow}</span><strong>{meta.label}</strong></div>
  </div>
}

function Panel({ mode, state, onState }: { mode: Mode; state: NexusState; onState: (s: NexusState) => void }) {
  if (mode === 'TASK') return <section className="mode-panel task-panel"><PanelHead eyebrow="ACTION LAYER" title="Workspace synthesis" /><div className="task-summary"><span>DEMO PRESENTATION STATE</span><strong>{state === 'success' ? 'Verified' : '3 / 4 steps'}</strong></div><div className="steps">{steps.map(([label, detail, status], index) => <div className={`step ${status} ${state === 'success' ? 'completed' : ''}`} key={label}><span className="step-number">{status === 'completed' || state === 'success' ? <Check size={12} /> : index + 1}</span><div><strong>{label}</strong><small>{detail}</small></div>{status === 'running' && state !== 'success' && <RotateCw className="step-spinner" size={13} />}</div>)}</div><div className="panel-actions"><button className="quiet-button" onClick={() => onState('recovery')}><CircleAlert size={14} /> Simulate recovery</button><button className="primary-button" onClick={() => onState('verifying')}><Zap size={14} /> Run verification</button></div></section>
  if (mode === 'ACTIVITY') return <section className="mode-panel"><PanelHead eyebrow="SYSTEM TIMELINE" title="Activity stream" /><div className="timeline"><TimelineIcon icon={<Check size={12} />} tone="success" title="Session initialized" detail="Core handshake complete · just now" /><TimelineIcon icon={<BrainCircuit size={12} />} title="Presentation state ready" detail="Waiting for a grounded capability" /><TimelineIcon icon={<Search size={12} />} tone="violet" title="Provenance layer armed" detail="Verification available on request" /><TimelineIcon icon={<ShieldCheck size={12} />} tone="muted" title="Privacy boundary intact" detail="Local session · protected" /></div></section>
  if (mode === 'EVIDENCE') return <section className="mode-panel"><PanelHead eyebrow="PROVENANCE LAYER" title="Evidence chain" /><div className="evidence-chain"><Evidence label="ANSWER" detail="Response presentation state" icon={<Sparkles size={13} />} /><Evidence label="WHY" detail="Context inspected by Nexus" icon={<BrainCircuit size={13} />} /><Evidence label="SOURCE" detail="No external source attached" icon={<FileText size={13} />} empty /><Evidence label="VERIFICATION" detail="Run verification to inspect" icon={<ShieldCheck size={13} />} /></div><div className="demo-note"><Eye size={14} /> Evidence is a presentation-layer demo until provenance is connected.</div></section>
  if (mode === 'SYSTEM') return <section className="mode-panel"><PanelHead eyebrow="CAPABILITY INSPECTOR" title="System status" /><div className="system-grid"><SystemItem icon={<BrainCircuit size={14} />} label="Model provider" value="Gemini Flash" status="AVAILABLE" /><SystemItem icon={<TerminalSquare size={14} />} label="Command interface" value="Presentation layer" status="READY" /><SystemItem icon={<Database size={14} />} label="Workspace context" value="Read only" status="AVAILABLE" /><SystemItem icon={<Mic size={14} />} label="Voice interaction" value="Future capability" status="PLANNED" /><SystemItem icon={<LockKeyhole size={14} />} label="Privacy state" value="Local session" status="PROTECTED" /><SystemItem icon={<Activity size={14} />} label="Backend event stream" value="Not connected" status="UNAVAILABLE" /></div></section>
  return <section className="mode-panel conversation-panel"><PanelHead eyebrow="CONVERSATION ENVIRONMENT" title="Ready when you are" /><div className="conversation-empty"><div className="empty-orbit"><Sparkles size={18} /></div><strong>Direct the Core</strong><p>Use the command field below to begin. Your presentation state will remain visible as the environment responds.</p></div></section>
}
function PanelHead({ eyebrow, title }: { eyebrow: string; title: string }) { return <div className="mode-panel-head"><div><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div><ChevronDown size={15} /></div> }
function TimelineIcon({ icon, title, detail, tone = 'cyan' }: { icon: React.ReactNode; title: string; detail: string; tone?: string }) { return <div className="timeline-item"><span className={`timeline-icon ${tone}`}>{icon}</span><div><strong>{title}</strong><small>{detail}</small></div><span className="timeline-line" /></div> }
function Evidence({ label, detail, icon, empty }: { label: string; detail: string; icon: React.ReactNode; empty?: boolean }) { return <button className={`evidence-row ${empty ? 'is-empty' : ''}`}><span className="evidence-icon">{icon}</span><span><b>{label}</b><small>{detail}</small></span><ArrowUpRight size={13} /></button> }
function SystemItem({ icon, label, value, status }: { icon: React.ReactNode; label: string; value: string; status: string }) { return <div className="system-item"><span className="system-icon">{icon}</span><div><strong>{label}</strong><small>{value}</small></div><b className={status === 'UNAVAILABLE' || status === 'PLANNED' ? 'muted-status' : ''}>{status}</b></div> }

function App() {
  const [state, setState] = useState<NexusState>('idle')
  const [mode, setMode] = useState<Mode>('CONVERSATION')
  const [command, setCommand] = useState('')
  const [response, setResponse] = useState('')
  const [connected, setConnected] = useState(true)
  const [showContext, setShowContext] = useState(true)
  const [time, setTime] = useState(new Date())
  const inputRef = useRef<HTMLInputElement>(null)
  useEffect(() => { const timer = window.setInterval(() => setTime(new Date()), 1000); return () => window.clearInterval(timer) }, [])
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'k') { event.preventDefault(); inputRef.current?.focus() } if (event.key === 'Escape') { setMode('CONVERSATION'); setState('idle') } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) }, [])
  const dateLabel = useMemo(() => time.toLocaleDateString([], { weekday: 'short', month: 'short', day: 'numeric' }).toUpperCase(), [time])
  const submitCommand = () => { if (!command.trim() || state === 'processing') return; setState('processing'); setResponse(''); setMode('CONVERSATION'); window.setTimeout(() => { setResponse('I’m ready to work through that with you. The presentation layer is connected and waiting for a Nexus Core capability to take over.'); setState('responding') }, 900) }
  const activateState = (next: NexusState) => { setState(next); if (next === 'success') window.setTimeout(() => setState('idle'), 2200) }
  const modes: Mode[] = ['CONVERSATION', 'TASK', 'ACTIVITY', 'EVIDENCE', 'SYSTEM']
  return <div className={`nexus-app environment-${state} mode-${mode.toLowerCase()}`}>
    <div className="ambient ambient-a" /><div className="ambient ambient-b" /><div className="grid-plane" /><div className="noise" />
    <header className="topbar"><div className="brand"><div className="brand-mark"><Cpu size={17} /></div><div><div className="brand-name">NEXUS <span>01</span></div><div className="brand-sub">PERSONAL INTELLIGENCE SYSTEM</div></div></div><div className="topbar-center"><span className="live-dot" /> CORE ONLINE <span className="topbar-divider" /> SESSION 08A4</div><div className="topbar-actions"><span className="clock"><span>{dateLabel}</span>{time.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span><button className="icon-button" aria-label="Focus command input" onClick={() => inputRef.current?.focus()}><Command size={16} /></button><button className="icon-button" aria-label="Toggle context panel" onClick={() => setShowContext(!showContext)}><MoreHorizontal size={17} /></button></div></header>
    <main className="main-layout"><section className="hero-column"><div className="hero-heading"><div><div className="kicker"><span className="kicker-line" /> PERSONAL OPERATING ENVIRONMENT</div><h1>Good evening, <em>Bilal.</em></h1><p>The Core is calm. Give it a direction.</p></div><div className="hero-actions"><button className={`quiet-button ${state === 'listening' ? 'is-active' : ''}`} onClick={() => activateState('listening')}><Mic size={15} /> {state === 'listening' ? 'Listening' : 'Voice ready'}</button><button className="quiet-button" onClick={() => setConnected(!connected)}><span className={`status-ring ${connected ? 'is-on' : ''}`} /> {connected ? 'Connected' : 'Offline'}</button></div></div>
      <div className="core-wrap"><Core state={state} /><div className="core-side-note note-left"><span>LATENCY</span><strong>24<span>ms</span></strong><i /></div><div className="core-side-note note-right"><span>UPTIME</span><strong>99.8<span>%</span></strong><i /></div></div>
      <nav className="mode-switcher" aria-label="Nexus environment modes"><span className="mode-label">OPERATING CONTEXT</span>{modes.map(item => <button key={item} className={mode === item ? 'active' : ''} onClick={() => { setMode(item); if (item === 'TASK') activateState('executing'); else if (item === 'EVIDENCE') activateState('verifying'); else setState('idle') }}>{item}</button>)}</nav>
      <div className="command-wrap"><div className="command-meta"><span><span className="pulse-dot" /> {state === 'processing' ? 'PROCESSING INPUT' : state === 'responding' ? 'RESPONSE READY' : 'READY FOR INPUT'}</span><span className="mono">⌘ K</span></div><div className="command-box"><Sparkles size={18} className="command-icon" /><input ref={inputRef} value={command} onChange={e => setCommand(e.target.value)} onKeyDown={e => { if (e.key === 'Enter' && !e.shiftKey && !e.nativeEvent.isComposing && e.keyCode !== 229) { e.preventDefault(); submitCommand() } }} placeholder="Ask Nexus anything..." aria-label="Command Nexus" /><button className="mic-button" onClick={() => activateState('listening')} aria-label="Start voice input"><Mic size={17} /></button><button className="send-button" onClick={submitCommand} disabled={!command.trim() || state === 'processing'} aria-label="Send command"><Send size={16} /></button></div><div className="command-hint">Try <button onClick={() => setCommand('Summarize my current workspace')}>“Summarize my current workspace”</button><span>or</span><button onClick={() => setCommand('Prepare a research brief')}>“Prepare a research brief”</button></div></div>
      {response && <div className="response-card"><div className="response-top"><span><Sparkles size={14} /> NEXUS RESPONSE</span><button onClick={() => { setResponse(''); setState('idle') }} aria-label="Dismiss response"><X size={14} /></button></div><p>{response}</p><div className="response-foot"><span><ShieldCheck size={13} /> Presentation layer · no external action taken</span><button onClick={() => { setMode('TASK'); activateState('executing') }}>Continue <ArrowUpRight size={13} /></button></div></div>}
      <Panel mode={mode} state={state} onState={activateState} />
    </section>
    {showContext && <aside className="context-panel"><div className="panel-header"><div><span className="eyebrow">CONTEXT LAYER</span><h2>System overview</h2></div><button className="icon-button" onClick={() => setShowContext(false)} aria-label="Hide context panel"><PanelRight size={16} /></button></div><div className="signal-card"><div className="signal-header"><span className="signal-icon"><Activity size={15} /></span><div><strong>Core readiness</strong><span>State synchronized</span></div><span className="signal-value">98%</span></div><div className="signal-bar"><i /></div><div className="signal-footer"><span>NEURAL ROUTER</span><span>{stateMeta[state].label.toUpperCase()}</span></div></div><div className="panel-section"><div className="section-title"><span>ACTIVE CAPABILITIES</span><button aria-label="Inspect capabilities" onClick={() => setMode('SYSTEM')}><Plus size={14} /></button></div><div className="capability"><span className="cap-icon"><TerminalSquare size={14} /></span><div><strong>Command interface</strong><small>Available · ready</small></div><span className="available" /></div><div className="capability"><span className="cap-icon"><Database size={14} /></span><div><strong>Workspace context</strong><small>Available · read only</small></div><span className="available" /></div><div className="capability muted"><span className="cap-icon"><Mic size={14} /></span><div><strong>Voice interaction</strong><small>Planned · not active</small></div><span className="planned" /></div></div><div className="panel-section"><div className="section-title"><span>RECENT ACTIVITY</span><button aria-label="Refresh activity" onClick={() => activateState('verifying')}><RotateCw size={13} /></button></div><button className="activity-row" onClick={() => setMode('ACTIVITY')}><span className="activity-mark success"><Check size={12} /></span><div><strong>Session initialized</strong><small>Just now · Core handshake complete</small></div></button><button className="activity-row" onClick={() => setMode('EVIDENCE')}><span className="activity-mark"><Clock3 size={12} /></span><div><strong>{stateMeta[state].label}</strong><small>Presentation event · inspect</small></div></button></div><div className="panel-footer"><div className="privacy"><ShieldCheck size={14} /><span><strong>Privacy mode</strong><small>Local session · protected</small></span></div><button className="text-button" onClick={() => setMode('SYSTEM')}>View details <ArrowUpRight size={13} /></button></div></aside>}
    {!showContext && <button className="reveal-panel" onClick={() => setShowContext(true)} aria-label="Show context panel"><PanelRight size={15} /></button>}</main>
    <footer className="footerbar"><span><Layers3 size={13} /> NEXUS PRESENTATION LAYER</span><span>MODEL <strong>GEMINI FLASH</strong></span><span>BUILD <strong>1.1.1</strong></span><span className="footer-spacer" /><span><FileText size={13} /> PROVENANCE READY</span></footer>
  </div>
}
export default App
